installCRDs: true

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 200Mi

webhook:
  enabled: true
  failurePolicy: Ignore
  manageCerts: true

config:
  logVerbosity: "0"
  metrics:
    port: 9090 
