apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
type: Opaque
stringData:
  DATA_SOURCE_NAME: "postgresql://prometheus:password@database-service.default.svc.cluster.local:5432/postgres?sslmode=disable"

