apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: incident
  template:
    metadata:
      labels:
        app: incident
    spec:
      containers:
        - name: incident
          image: vishnu4538/main_app:v5
          ports:
            - containerPort: 8000
