groups:
  - name: test-alerts
    rules:
      - alert: AlwaysFiring
        expr: vector(1)
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "This is a test alert"
          description: "Testing Alertmanager integration"

