---
# Source: prometheus/charts/prometheus-pushgateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    helm.sh/chart: prometheus-pushgateway-3.8.0
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/instance: prometheus-community
    app.kubernetes.io/version: "v1.11.3"
    app.kubernetes.io/managed-by: Helm  
  name: prometheus-community-prometheus-pushgateway
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-pushgateway
      app.kubernetes.io/instance: prometheus-community
  template:
    metadata:
      labels:
        helm.sh/chart: prometheus-pushgateway-3.8.0
        app.kubernetes.io/name: prometheus-pushgateway
        app.kubernetes.io/instance: prometheus-community
        app.kubernetes.io/version: "v1.11.3"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: prometheus-community-prometheus-pushgateway
      automountServiceAccountToken: true
      containers:
        - name: pushgateway
          image: quay.io/prometheus/pushgateway:v1.11.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9091
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9091
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 10
          volumeMounts:
            - name: storage-volume
              mountPath: "/data"
              subPath: ""
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      volumes:
        - name: storage-volume
          emptyDir:
            {}
